// <auto-generated />
using System;
using ArManBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArManBank.Data.Migrations
{
    [DbContext(typeof(ArManBankDbContext))]
    [Migration("20250505163956_FeedDbData")]
    partial class FeedDbData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ArManBank.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeOfBalance")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1340.75m,
                            CreateDate = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Doe",
                            TypeOfBalance = 0
                        },
                        new
                        {
                            Id = 2,
                            Balance = 987.60m,
                            CreateDate = new DateTime(2023, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emma",
                            LastName = "Smith",
                            TypeOfBalance = 0
                        },
                        new
                        {
                            Id = 3,
                            Balance = 2590.00m,
                            CreateDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Liam",
                            LastName = "Johnson",
                            TypeOfBalance = 2
                        },
                        new
                        {
                            Id = 4,
                            Balance = 410.50m,
                            CreateDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Olivia",
                            LastName = "Brown",
                            TypeOfBalance = 1
                        },
                        new
                        {
                            Id = 5,
                            Balance = 1325.25m,
                            CreateDate = new DateTime(2023, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Noah",
                            LastName = "Williams",
                            TypeOfBalance = 0
                        },
                        new
                        {
                            Id = 6,
                            Balance = 830.80m,
                            CreateDate = new DateTime(2023, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ava",
                            LastName = "Jones",
                            TypeOfBalance = 1
                        },
                        new
                        {
                            Id = 7,
                            Balance = 4200.00m,
                            CreateDate = new DateTime(2023, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            LastName = "Miller",
                            TypeOfBalance = 2
                        },
                        new
                        {
                            Id = 8,
                            Balance = 1550.30m,
                            CreateDate = new DateTime(2023, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Isabella",
                            LastName = "Davis",
                            TypeOfBalance = 0
                        },
                        new
                        {
                            Id = 9,
                            Balance = 670.00m,
                            CreateDate = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            LastName = "Garcia",
                            TypeOfBalance = 0
                        },
                        new
                        {
                            Id = 10,
                            Balance = 2999.99m,
                            CreateDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophia",
                            LastName = "Martinez",
                            TypeOfBalance = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
